[project]
name = "semi-seg-ecg-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mergedeep",
    "einops",
    "numpy",
    "pandas",
    "PyYAML",
    "scikit-learn",
    "scipy",
    "torch",
    "tqdm",
    "wfdb",
    "tensorboard",
    "torchmetrics",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true